import IconNotoV1DarkSkinTone from './IconNotoV1DarkSkinTone'
import IconNotoV1LightSkinTone from './IconNotoV1LightSkinTone'
import IconNotoV1MediumDarkSkinTone from './IconNotoV1MediumDarkSkinTone'
import IconNotoV1MediumLightSkinTone from './IconNotoV1MediumLightSkinTone'
import IconNotoV1MediumSkinTone from './IconNotoV1MediumSkinTone'
import IconNotoV1AButton from './IconNotoV1AButton'
import IconNotoV1AbButton from './IconNotoV1AbButton'
import IconNotoV1AnticlockwiseArrowsButton from './IconNotoV1AnticlockwiseArrowsButton'
import IconNotoV1BButton from './IconNotoV1BButton'
import IconNotoV1BallotBoxWithCheck from './IconNotoV1BallotBoxWithCheck'
import IconNotoV1BearFace from './IconNotoV1BearFace'
import IconNotoV1BlondHairedMan from './IconNotoV1BlondHairedMan'
import IconNotoV1BlondHairedManDarkSkinTone from './IconNotoV1BlondHairedManDarkSkinTone'
import IconNotoV1BlondHairedManLightSkinTone from './IconNotoV1BlondHairedManLightSkinTone'
import IconNotoV1BlondHairedManMediumDarkSkinTone from './IconNotoV1BlondHairedManMediumDarkSkinTone'
import IconNotoV1BlondHairedManMediumLightSkinTone from './IconNotoV1BlondHairedManMediumLightSkinTone'
import IconNotoV1BlondHairedManMediumSkinTone from './IconNotoV1BlondHairedManMediumSkinTone'
import IconNotoV1BlondHairedPerson from './IconNotoV1BlondHairedPerson'
import IconNotoV1BlondHairedPersonDarkSkinTone from './IconNotoV1BlondHairedPersonDarkSkinTone'
import IconNotoV1BlondHairedPersonLightSkinTone from './IconNotoV1BlondHairedPersonLightSkinTone'
import IconNotoV1BlondHairedPersonMediumDarkSkinTone from './IconNotoV1BlondHairedPersonMediumDarkSkinTone'
import IconNotoV1BlondHairedPersonMediumLightSkinTone from './IconNotoV1BlondHairedPersonMediumLightSkinTone'
import IconNotoV1BlondHairedPersonMediumSkinTone from './IconNotoV1BlondHairedPersonMediumSkinTone'
import IconNotoV1BlondHairedWoman from './IconNotoV1BlondHairedWoman'
import IconNotoV1BlondHairedWomanDarkSkinTone from './IconNotoV1BlondHairedWomanDarkSkinTone'
import IconNotoV1BlondHairedWomanLightSkinTone from './IconNotoV1BlondHairedWomanLightSkinTone'
import IconNotoV1BlondHairedWomanMediumDarkSkinTone from './IconNotoV1BlondHairedWomanMediumDarkSkinTone'
import IconNotoV1BlondHairedWomanMediumLightSkinTone from './IconNotoV1BlondHairedWomanMediumLightSkinTone'
import IconNotoV1BlondHairedWomanMediumSkinTone from './IconNotoV1BlondHairedWomanMediumSkinTone'
import IconNotoV1BrideWithVeil from './IconNotoV1BrideWithVeil'
import IconNotoV1BrideWithVeilDarkSkinTone from './IconNotoV1BrideWithVeilDarkSkinTone'
import IconNotoV1BrideWithVeilLightSkinTone from './IconNotoV1BrideWithVeilLightSkinTone'
import IconNotoV1BrideWithVeilMediumDarkSkinTone from './IconNotoV1BrideWithVeilMediumDarkSkinTone'
import IconNotoV1BrideWithVeilMediumLightSkinTone from './IconNotoV1BrideWithVeilMediumLightSkinTone'
import IconNotoV1BrideWithVeilMediumSkinTone from './IconNotoV1BrideWithVeilMediumSkinTone'
import IconNotoV1CatFaceWithTearsOfJoy from './IconNotoV1CatFaceWithTearsOfJoy'
import IconNotoV1CatFaceWithWrySmile from './IconNotoV1CatFaceWithWrySmile'
import IconNotoV1Cricket from './IconNotoV1Cricket'
import IconNotoV1CryingCatFace from './IconNotoV1CryingCatFace'
import IconNotoV1DisappointedButRelievedFace from './IconNotoV1DisappointedButRelievedFace'
import IconNotoV1DivisionSign from './IconNotoV1DivisionSign'
import IconNotoV1DownButton from './IconNotoV1DownButton'
import IconNotoV1FaceSavouringDeliciousFood from './IconNotoV1FaceSavouringDeliciousFood'
import IconNotoV1FaceWithColdSweat from './IconNotoV1FaceWithColdSweat'
import IconNotoV1FaceWithOpenMouthAndColdSweat from './IconNotoV1FaceWithOpenMouthAndColdSweat'
import IconNotoV1FaceWithStuckOutTongue from './IconNotoV1FaceWithStuckOutTongue'
import IconNotoV1FaceWithStuckOutTongueAndClosedEyes from './IconNotoV1FaceWithStuckOutTongueAndClosedEyes'
import IconNotoV1FaceWithStuckOutTongueAndWinkingEye from './IconNotoV1FaceWithStuckOutTongueAndWinkingEye'
import IconNotoV1FirstQuarterMoonWithFace from './IconNotoV1FirstQuarterMoonWithFace'
import IconNotoV1FlagForBlackFlag from './IconNotoV1FlagForBlackFlag'
import IconNotoV1FlagForChequeredFlag from './IconNotoV1FlagForChequeredFlag'
import IconNotoV1FlagForChina from './IconNotoV1FlagForChina'
import IconNotoV1FlagForCrossedFlags from './IconNotoV1FlagForCrossedFlags'
import IconNotoV1FlagForFrance from './IconNotoV1FlagForFrance'
import IconNotoV1FlagForGermany from './IconNotoV1FlagForGermany'
import IconNotoV1FlagForItaly from './IconNotoV1FlagForItaly'
import IconNotoV1FlagForJapan from './IconNotoV1FlagForJapan'
import IconNotoV1FlagForRussia from './IconNotoV1FlagForRussia'
import IconNotoV1FlagForSouthKorea from './IconNotoV1FlagForSouthKorea'
import IconNotoV1FlagForSpain from './IconNotoV1FlagForSpain'
import IconNotoV1FlagForTriangularFlag from './IconNotoV1FlagForTriangularFlag'
import IconNotoV1FlagForUnitedKingdom from './IconNotoV1FlagForUnitedKingdom'
import IconNotoV1FlagForUnitedStates from './IconNotoV1FlagForUnitedStates'
import IconNotoV1FlagForWhiteFlag from './IconNotoV1FlagForWhiteFlag'
import IconNotoV1FoxFace from './IconNotoV1FoxFace'
import IconNotoV1FrogFace from './IconNotoV1FrogFace'
import IconNotoV1FullMoonWithFace from './IconNotoV1FullMoonWithFace'
import IconNotoV1GrinningCatFace from './IconNotoV1GrinningCatFace'
import IconNotoV1GrinningCatFaceWithSmilingEyes from './IconNotoV1GrinningCatFaceWithSmilingEyes'
import IconNotoV1HamsterFace from './IconNotoV1HamsterFace'
import IconNotoV1HandshakeTone1 from './IconNotoV1HandshakeTone1'
import IconNotoV1HandshakeTone2 from './IconNotoV1HandshakeTone2'
import IconNotoV1HandshakeTone3 from './IconNotoV1HandshakeTone3'
import IconNotoV1HandshakeTone4 from './IconNotoV1HandshakeTone4'
import IconNotoV1HandshakeTone5 from './IconNotoV1HandshakeTone5'
import IconNotoV1HeavyCheckMark from './IconNotoV1HeavyCheckMark'
import IconNotoV1HeavyDivisionSign from './IconNotoV1HeavyDivisionSign'
import IconNotoV1HeavyHeartExclamation from './IconNotoV1HeavyHeartExclamation'
import IconNotoV1HeavyLargeCircle from './IconNotoV1HeavyLargeCircle'
import IconNotoV1HeavyMinusSign from './IconNotoV1HeavyMinusSign'
import IconNotoV1HeavyMultiplicationX from './IconNotoV1HeavyMultiplicationX'
import IconNotoV1HeavyPlusSign from './IconNotoV1HeavyPlusSign'
import IconNotoV1HighSpeedTrainWithBulletNose from './IconNotoV1HighSpeedTrainWithBulletNose'
import IconNotoV1Hourglass from './IconNotoV1Hourglass'
import IconNotoV1HourglassWithFlowingSand from './IconNotoV1HourglassWithFlowingSand'
import IconNotoV1KissingCatFace from './IconNotoV1KissingCatFace'
import IconNotoV1KissingCatFaceWithClosedEyes from './IconNotoV1KissingCatFaceWithClosedEyes'
import IconNotoV1LaptopComputer from './IconNotoV1LaptopComputer'
import IconNotoV1LastQuarterMoonWithFace from './IconNotoV1LastQuarterMoonWithFace'
import IconNotoV1LeftPointingMagnifyingGlass from './IconNotoV1LeftPointingMagnifyingGlass'
import IconNotoV1LionFace from './IconNotoV1LionFace'
import IconNotoV1ManAndWomanHoldingHands from './IconNotoV1ManAndWomanHoldingHands'
import IconNotoV1ManInBusinessSuitLevitating from './IconNotoV1ManInBusinessSuitLevitating'
import IconNotoV1ManInSuitLevitating from './IconNotoV1ManInSuitLevitating'
import IconNotoV1ManInTuxedo from './IconNotoV1ManInTuxedo'
import IconNotoV1ManInTuxedoDarkSkinTone from './IconNotoV1ManInTuxedoDarkSkinTone'
import IconNotoV1ManInTuxedoLightSkinTone from './IconNotoV1ManInTuxedoLightSkinTone'
import IconNotoV1ManInTuxedoMediumDarkSkinTone from './IconNotoV1ManInTuxedoMediumDarkSkinTone'
import IconNotoV1ManInTuxedoMediumLightSkinTone from './IconNotoV1ManInTuxedoMediumLightSkinTone'
import IconNotoV1ManInTuxedoMediumSkinTone from './IconNotoV1ManInTuxedoMediumSkinTone'
import IconNotoV1ManWithChineseCap from './IconNotoV1ManWithChineseCap'
import IconNotoV1ManWithChineseCapDarkSkinTone from './IconNotoV1ManWithChineseCapDarkSkinTone'
import IconNotoV1ManWithChineseCapLightSkinTone from './IconNotoV1ManWithChineseCapLightSkinTone'
import IconNotoV1ManWithChineseCapMediumDarkSkinTone from './IconNotoV1ManWithChineseCapMediumDarkSkinTone'
import IconNotoV1ManWithChineseCapMediumLightSkinTone from './IconNotoV1ManWithChineseCapMediumLightSkinTone'
import IconNotoV1ManWithChineseCapMediumSkinTone from './IconNotoV1ManWithChineseCapMediumSkinTone'
import IconNotoV1ManWithSkullcap from './IconNotoV1ManWithSkullcap'
import IconNotoV1ManWithSkullcapDarkSkinTone from './IconNotoV1ManWithSkullcapDarkSkinTone'
import IconNotoV1ManWithSkullcapLightSkinTone from './IconNotoV1ManWithSkullcapLightSkinTone'
import IconNotoV1ManWithSkullcapMediumDarkSkinTone from './IconNotoV1ManWithSkullcapMediumDarkSkinTone'
import IconNotoV1ManWithSkullcapMediumLightSkinTone from './IconNotoV1ManWithSkullcapMediumLightSkinTone'
import IconNotoV1ManWithSkullcapMediumSkinTone from './IconNotoV1ManWithSkullcapMediumSkinTone'
import IconNotoV1MenWithBunnyEarsPartying from './IconNotoV1MenWithBunnyEarsPartying'
import IconNotoV1MenWrestlingTone1 from './IconNotoV1MenWrestlingTone1'
import IconNotoV1MenWrestlingTone2 from './IconNotoV1MenWrestlingTone2'
import IconNotoV1MenWrestlingTone3 from './IconNotoV1MenWrestlingTone3'
import IconNotoV1MenWrestlingTone4 from './IconNotoV1MenWrestlingTone4'
import IconNotoV1MenWrestlingTone5 from './IconNotoV1MenWrestlingTone5'
import IconNotoV1MinusSign from './IconNotoV1MinusSign'
import IconNotoV1MultiplicationSign from './IconNotoV1MultiplicationSign'
import IconNotoV1OButton from './IconNotoV1OButton'
import IconNotoV1OnArrow from './IconNotoV1OnArrow'
import IconNotoV1PandaFace from './IconNotoV1PandaFace'
import IconNotoV1PeopleWithBunnyEarsPartying from './IconNotoV1PeopleWithBunnyEarsPartying'
import IconNotoV1PeopleWrestlingTone1 from './IconNotoV1PeopleWrestlingTone1'
import IconNotoV1PeopleWrestlingTone2 from './IconNotoV1PeopleWrestlingTone2'
import IconNotoV1PeopleWrestlingTone3 from './IconNotoV1PeopleWrestlingTone3'
import IconNotoV1PeopleWrestlingTone4 from './IconNotoV1PeopleWrestlingTone4'
import IconNotoV1PeopleWrestlingTone5 from './IconNotoV1PeopleWrestlingTone5'
import IconNotoV1PlusSign from './IconNotoV1PlusSign'
import IconNotoV1PoutingCatFace from './IconNotoV1PoutingCatFace'
import IconNotoV1RaisedHandWithFingersSplayed from './IconNotoV1RaisedHandWithFingersSplayed'
import IconNotoV1RaisedHandWithFingersSplayedDarkSkinTone from './IconNotoV1RaisedHandWithFingersSplayedDarkSkinTone'
import IconNotoV1RaisedHandWithFingersSplayedLightSkinTone from './IconNotoV1RaisedHandWithFingersSplayedLightSkinTone'
import IconNotoV1RaisedHandWithFingersSplayedMediumDarkSkinTone from './IconNotoV1RaisedHandWithFingersSplayedMediumDarkSkinTone'
import IconNotoV1RaisedHandWithFingersSplayedMediumLightSkinTone from './IconNotoV1RaisedHandWithFingersSplayedMediumLightSkinTone'
import IconNotoV1RaisedHandWithFingersSplayedMediumSkinTone from './IconNotoV1RaisedHandWithFingersSplayedMediumSkinTone'
import IconNotoV1RightPointingMagnifyingGlass from './IconNotoV1RightPointingMagnifyingGlass'
import IconNotoV1RobotFace from './IconNotoV1RobotFace'
import IconNotoV1SchoolBackpack from './IconNotoV1SchoolBackpack'
import IconNotoV1Scorpius from './IconNotoV1Scorpius'
import IconNotoV1SmilingCatFaceWithHeartEyes from './IconNotoV1SmilingCatFaceWithHeartEyes'
import IconNotoV1SmilingCatFaceWithOpenMouth from './IconNotoV1SmilingCatFaceWithOpenMouth'
import IconNotoV1SmilingFaceWithOpenMouth from './IconNotoV1SmilingFaceWithOpenMouth'
import IconNotoV1SmilingFaceWithOpenMouthAndClosedEyes from './IconNotoV1SmilingFaceWithOpenMouthAndClosedEyes'
import IconNotoV1SmilingFaceWithOpenMouthAndColdSweat from './IconNotoV1SmilingFaceWithOpenMouthAndColdSweat'
import IconNotoV1SmilingFaceWithOpenMouthAndSmilingEyes from './IconNotoV1SmilingFaceWithOpenMouthAndSmilingEyes'
import IconNotoV1TwoMenHoldingHands from './IconNotoV1TwoMenHoldingHands'
import IconNotoV1TwoWomenHoldingHands from './IconNotoV1TwoWomenHoldingHands'
import IconNotoV1UnicornFace from './IconNotoV1UnicornFace'
import IconNotoV1UpButton from './IconNotoV1UpButton'
import IconNotoV1UpTextButton from './IconNotoV1UpTextButton'
import IconNotoV1WearyCatFace from './IconNotoV1WearyCatFace'
import IconNotoV1WhiteHeavyCheckMark from './IconNotoV1WhiteHeavyCheckMark'
import IconNotoV1WhiteMediumStar from './IconNotoV1WhiteMediumStar'
import IconNotoV1WolfFace from './IconNotoV1WolfFace'
import IconNotoV1WomenWithBunnyEarsPartying from './IconNotoV1WomenWithBunnyEarsPartying'
import IconNotoV1WomenWrestlingTone1 from './IconNotoV1WomenWrestlingTone1'
import IconNotoV1WomenWrestlingTone2 from './IconNotoV1WomenWrestlingTone2'
import IconNotoV1WomenWrestlingTone3 from './IconNotoV1WomenWrestlingTone3'
import IconNotoV1WomenWrestlingTone4 from './IconNotoV1WomenWrestlingTone4'
import IconNotoV1WomenWrestlingTone5 from './IconNotoV1WomenWrestlingTone5'
export default {
	IconNotoV1DarkSkinTone,
	IconNotoV1LightSkinTone,
	IconNotoV1MediumDarkSkinTone,
	IconNotoV1MediumLightSkinTone,
	IconNotoV1MediumSkinTone,
	IconNotoV1AButton,
	IconNotoV1AbButton,
	IconNotoV1AnticlockwiseArrowsButton,
	IconNotoV1BButton,
	IconNotoV1BallotBoxWithCheck,
	IconNotoV1BearFace,
	IconNotoV1BlondHairedMan,
	IconNotoV1BlondHairedManDarkSkinTone,
	IconNotoV1BlondHairedManLightSkinTone,
	IconNotoV1BlondHairedManMediumDarkSkinTone,
	IconNotoV1BlondHairedManMediumLightSkinTone,
	IconNotoV1BlondHairedManMediumSkinTone,
	IconNotoV1BlondHairedPerson,
	IconNotoV1BlondHairedPersonDarkSkinTone,
	IconNotoV1BlondHairedPersonLightSkinTone,
	IconNotoV1BlondHairedPersonMediumDarkSkinTone,
	IconNotoV1BlondHairedPersonMediumLightSkinTone,
	IconNotoV1BlondHairedPersonMediumSkinTone,
	IconNotoV1BlondHairedWoman,
	IconNotoV1BlondHairedWomanDarkSkinTone,
	IconNotoV1BlondHairedWomanLightSkinTone,
	IconNotoV1BlondHairedWomanMediumDarkSkinTone,
	IconNotoV1BlondHairedWomanMediumLightSkinTone,
	IconNotoV1BlondHairedWomanMediumSkinTone,
	IconNotoV1BrideWithVeil,
	IconNotoV1BrideWithVeilDarkSkinTone,
	IconNotoV1BrideWithVeilLightSkinTone,
	IconNotoV1BrideWithVeilMediumDarkSkinTone,
	IconNotoV1BrideWithVeilMediumLightSkinTone,
	IconNotoV1BrideWithVeilMediumSkinTone,
	IconNotoV1CatFaceWithTearsOfJoy,
	IconNotoV1CatFaceWithWrySmile,
	IconNotoV1Cricket,
	IconNotoV1CryingCatFace,
	IconNotoV1DisappointedButRelievedFace,
	IconNotoV1DivisionSign,
	IconNotoV1DownButton,
	IconNotoV1FaceSavouringDeliciousFood,
	IconNotoV1FaceWithColdSweat,
	IconNotoV1FaceWithOpenMouthAndColdSweat,
	IconNotoV1FaceWithStuckOutTongue,
	IconNotoV1FaceWithStuckOutTongueAndClosedEyes,
	IconNotoV1FaceWithStuckOutTongueAndWinkingEye,
	IconNotoV1FirstQuarterMoonWithFace,
	IconNotoV1FlagForBlackFlag,
	IconNotoV1FlagForChequeredFlag,
	IconNotoV1FlagForChina,
	IconNotoV1FlagForCrossedFlags,
	IconNotoV1FlagForFrance,
	IconNotoV1FlagForGermany,
	IconNotoV1FlagForItaly,
	IconNotoV1FlagForJapan,
	IconNotoV1FlagForRussia,
	IconNotoV1FlagForSouthKorea,
	IconNotoV1FlagForSpain,
	IconNotoV1FlagForTriangularFlag,
	IconNotoV1FlagForUnitedKingdom,
	IconNotoV1FlagForUnitedStates,
	IconNotoV1FlagForWhiteFlag,
	IconNotoV1FoxFace,
	IconNotoV1FrogFace,
	IconNotoV1FullMoonWithFace,
	IconNotoV1GrinningCatFace,
	IconNotoV1GrinningCatFaceWithSmilingEyes,
	IconNotoV1HamsterFace,
	IconNotoV1HandshakeTone1,
	IconNotoV1HandshakeTone2,
	IconNotoV1HandshakeTone3,
	IconNotoV1HandshakeTone4,
	IconNotoV1HandshakeTone5,
	IconNotoV1HeavyCheckMark,
	IconNotoV1HeavyDivisionSign,
	IconNotoV1HeavyHeartExclamation,
	IconNotoV1HeavyLargeCircle,
	IconNotoV1HeavyMinusSign,
	IconNotoV1HeavyMultiplicationX,
	IconNotoV1HeavyPlusSign,
	IconNotoV1HighSpeedTrainWithBulletNose,
	IconNotoV1Hourglass,
	IconNotoV1HourglassWithFlowingSand,
	IconNotoV1KissingCatFace,
	IconNotoV1KissingCatFaceWithClosedEyes,
	IconNotoV1LaptopComputer,
	IconNotoV1LastQuarterMoonWithFace,
	IconNotoV1LeftPointingMagnifyingGlass,
	IconNotoV1LionFace,
	IconNotoV1ManAndWomanHoldingHands,
	IconNotoV1ManInBusinessSuitLevitating,
	IconNotoV1ManInSuitLevitating,
	IconNotoV1ManInTuxedo,
	IconNotoV1ManInTuxedoDarkSkinTone,
	IconNotoV1ManInTuxedoLightSkinTone,
	IconNotoV1ManInTuxedoMediumDarkSkinTone,
	IconNotoV1ManInTuxedoMediumLightSkinTone,
	IconNotoV1ManInTuxedoMediumSkinTone,
	IconNotoV1ManWithChineseCap,
	IconNotoV1ManWithChineseCapDarkSkinTone,
	IconNotoV1ManWithChineseCapLightSkinTone,
	IconNotoV1ManWithChineseCapMediumDarkSkinTone,
	IconNotoV1ManWithChineseCapMediumLightSkinTone,
	IconNotoV1ManWithChineseCapMediumSkinTone,
	IconNotoV1ManWithSkullcap,
	IconNotoV1ManWithSkullcapDarkSkinTone,
	IconNotoV1ManWithSkullcapLightSkinTone,
	IconNotoV1ManWithSkullcapMediumDarkSkinTone,
	IconNotoV1ManWithSkullcapMediumLightSkinTone,
	IconNotoV1ManWithSkullcapMediumSkinTone,
	IconNotoV1MenWithBunnyEarsPartying,
	IconNotoV1MenWrestlingTone1,
	IconNotoV1MenWrestlingTone2,
	IconNotoV1MenWrestlingTone3,
	IconNotoV1MenWrestlingTone4,
	IconNotoV1MenWrestlingTone5,
	IconNotoV1MinusSign,
	IconNotoV1MultiplicationSign,
	IconNotoV1OButton,
	IconNotoV1OnArrow,
	IconNotoV1PandaFace,
	IconNotoV1PeopleWithBunnyEarsPartying,
	IconNotoV1PeopleWrestlingTone1,
	IconNotoV1PeopleWrestlingTone2,
	IconNotoV1PeopleWrestlingTone3,
	IconNotoV1PeopleWrestlingTone4,
	IconNotoV1PeopleWrestlingTone5,
	IconNotoV1PlusSign,
	IconNotoV1PoutingCatFace,
	IconNotoV1RaisedHandWithFingersSplayed,
	IconNotoV1RaisedHandWithFingersSplayedDarkSkinTone,
	IconNotoV1RaisedHandWithFingersSplayedLightSkinTone,
	IconNotoV1RaisedHandWithFingersSplayedMediumDarkSkinTone,
	IconNotoV1RaisedHandWithFingersSplayedMediumLightSkinTone,
	IconNotoV1RaisedHandWithFingersSplayedMediumSkinTone,
	IconNotoV1RightPointingMagnifyingGlass,
	IconNotoV1RobotFace,
	IconNotoV1SchoolBackpack,
	IconNotoV1Scorpius,
	IconNotoV1SmilingCatFaceWithHeartEyes,
	IconNotoV1SmilingCatFaceWithOpenMouth,
	IconNotoV1SmilingFaceWithOpenMouth,
	IconNotoV1SmilingFaceWithOpenMouthAndClosedEyes,
	IconNotoV1SmilingFaceWithOpenMouthAndColdSweat,
	IconNotoV1SmilingFaceWithOpenMouthAndSmilingEyes,
	IconNotoV1TwoMenHoldingHands,
	IconNotoV1TwoWomenHoldingHands,
	IconNotoV1UnicornFace,
	IconNotoV1UpButton,
	IconNotoV1UpTextButton,
	IconNotoV1WearyCatFace,
	IconNotoV1WhiteHeavyCheckMark,
	IconNotoV1WhiteMediumStar,
	IconNotoV1WolfFace,
	IconNotoV1WomenWithBunnyEarsPartying,
	IconNotoV1WomenWrestlingTone1,
	IconNotoV1WomenWrestlingTone2,
	IconNotoV1WomenWrestlingTone3,
	IconNotoV1WomenWrestlingTone4,
	IconNotoV1WomenWrestlingTone5
}